import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const skillPath = join(__dirname, '..', '.agent', 'skills', 'den-mlm-coach', 'SKILL.md');
const outputPath = join(__dirname, 'app', 'lib', 'den-mlm-coach-skill.ts');

try {
  console.log(`🤖 Reading skill file from ${skillPath}...`);
  const content = readFileSync(skillPath, 'utf-8');
  
  // Escape backticks and backslashes for JS template string
  const escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');

  const tsContent = `/**
 * Generated automatically at build time from .agent/skills/den-mlm-coach/SKILL.md
 * Do not edit this file directly.
 */
export const denMlmCoachSkill = \`${escapedContent}\`;
`;

  writeFileSync(outputPath, tsContent, 'utf-8');
  console.log(`✅ Successfully generated ${outputPath}`);
} catch (err) {
  console.error('❌ Failed to prebuild skills:', err);
  process.exit(1);
}
