// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/ai-coach": {
    params: {};
  };
  "/dna": {
    params: {};
  };
  "/missions": {
    params: {};
  };
  "/startup": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/knowledge": {
    params: {};
  };
  "/functions": {
    params: {};
  };
  "/r/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/products/new": {
    params: {};
  };
  "/admin/products/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/knowledge": {
    params: {};
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/ai-coach": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
  "/api/notify": {
    params: {};
  };
  "/api/upload": {
    params: {};
  };
  "/api/referral/track": {
    params: {};
  };
  "/api/referral/claim": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/auth/callback" | "/dashboard" | "/profile" | "/ai-coach" | "/dna" | "/missions" | "/startup" | "/products" | "/knowledge" | "/functions" | "/r/:slug" | "/admin" | "/admin/products" | "/admin/products/new" | "/admin/products/:id" | "/admin/categories" | "/admin/knowledge" | "/api/auth/login" | "/api/ai-coach" | "/api/contact" | "/api/notify" | "/api/upload" | "/api/referral/track" | "/api/referral/claim";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/ai-coach.tsx": {
    id: "routes/ai-coach";
    page: "/ai-coach";
  };
  "routes/dna.tsx": {
    id: "routes/dna";
    page: "/dna";
  };
  "routes/missions.tsx": {
    id: "routes/missions";
    page: "/missions";
  };
  "routes/startup.tsx": {
    id: "routes/startup";
    page: "/startup";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/knowledge.tsx": {
    id: "routes/knowledge";
    page: "/knowledge";
  };
  "routes/functions.tsx": {
    id: "routes/functions";
    page: "/functions";
  };
  "routes/referral.$slug.tsx": {
    id: "routes/referral.$slug";
    page: "/r/:slug";
  };
  "routes/admin.dashboard.tsx": {
    id: "routes/admin.dashboard";
    page: "/admin";
  };
  "routes/admin.products.index.tsx": {
    id: "routes/admin.products.index";
    page: "/admin/products";
  };
  "routes/admin.products.new.tsx": {
    id: "routes/admin.products.new";
    page: "/admin/products/new";
  };
  "routes/admin.products.edit.tsx": {
    id: "routes/admin.products.edit";
    page: "/admin/products/:id";
  };
  "routes/admin.categories.tsx": {
    id: "routes/admin.categories";
    page: "/admin/categories";
  };
  "routes/admin.knowledge.tsx": {
    id: "routes/admin.knowledge";
    page: "/admin/knowledge";
  };
  "routes/api.auth.login.ts": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.ai-coach.ts": {
    id: "routes/api.ai-coach";
    page: "/api/ai-coach";
  };
  "routes/api.contact.ts": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
  "routes/api.notify.ts": {
    id: "routes/api.notify";
    page: "/api/notify";
  };
  "routes/api.upload.ts": {
    id: "routes/api.upload";
    page: "/api/upload";
  };
  "routes/api.referral.track.ts": {
    id: "routes/api.referral.track";
    page: "/api/referral/track";
  };
  "routes/api.referral.claim.ts": {
    id: "routes/api.referral.claim";
    page: "/api/referral/claim";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/ai-coach": typeof import("./app/routes/ai-coach.tsx");
  "routes/dna": typeof import("./app/routes/dna.tsx");
  "routes/missions": typeof import("./app/routes/missions.tsx");
  "routes/startup": typeof import("./app/routes/startup.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/knowledge": typeof import("./app/routes/knowledge.tsx");
  "routes/functions": typeof import("./app/routes/functions.tsx");
  "routes/referral.$slug": typeof import("./app/routes/referral.$slug.tsx");
  "routes/admin.dashboard": typeof import("./app/routes/admin.dashboard.tsx");
  "routes/admin.products.index": typeof import("./app/routes/admin.products.index.tsx");
  "routes/admin.products.new": typeof import("./app/routes/admin.products.new.tsx");
  "routes/admin.products.edit": typeof import("./app/routes/admin.products.edit.tsx");
  "routes/admin.categories": typeof import("./app/routes/admin.categories.tsx");
  "routes/admin.knowledge": typeof import("./app/routes/admin.knowledge.tsx");
  "routes/api.auth.login": typeof import("./app/routes/api.auth.login.ts");
  "routes/api.ai-coach": typeof import("./app/routes/api.ai-coach.ts");
  "routes/api.contact": typeof import("./app/routes/api.contact.ts");
  "routes/api.notify": typeof import("./app/routes/api.notify.ts");
  "routes/api.upload": typeof import("./app/routes/api.upload.ts");
  "routes/api.referral.track": typeof import("./app/routes/api.referral.track.ts");
  "routes/api.referral.claim": typeof import("./app/routes/api.referral.claim.ts");
};